### ISSUE TITLE
Error when import the package

### ISSUE THREAD

**Issue by mghifariy** [sweetalert2/sweetalert2-react-content#30]
I am just do `import Swal from 'sweetalert2';`
and there's error with this message:
> undefined is not a function (evaluating 'Object.setPrototypeOf(NoNewKeywordSwal, ParentSwal)')

so what happens?

**Comment by zenflow** [comment]
Hi @mghifariy I think this is an issue for the core repo, probably related to #1062 which is in sweetalert2 v7.19.1 .. Try upgrading and if it's still malfunctioning open an issue in the sweetalert2 repo

**Comment by limonte** [comment]
I'm not sure that 

> undefined is not a function (evaluating 'Object.setPrototypeOf(NoNewKeywordSwal, ParentSwal)')

when doing `import Swal from 'sweetalert2'` is related to https://github.com/sweetalert2/sweetalert2/pull/1062

https://github.com/sweetalert2/sweetalert2/pull/1062 is related only to `.min.js` files, and `import Swal from 'sweetalert2'` is using `dist/sweetalert2.all.js`, https://github.com/sweetalert2/sweetalert2/blob/master/package.json#L7

Just to confirm, @mghifariy do you still have that issue after upgrading to v7.19.1?

**Comment by limonte** [comment]
@mghifariy sorry about that, this repo is relatively young and we didn't yet add the installation guide.

The installation is:

```bash
npm install --save sweetalert2 sweetalert2-react-content
```

I added the corresponding PR: https://github.com/sweetalert2/sweetalert2-react-content/pull/31

**Comment by zenflow** [comment]
Seems like we're still confusing this package and the core sweetalert2 package. The problem according to the original issue is that importing `sweetalert2` throws this error, which I think is correct since `sweetalert2-react-content` doesn't have that code with the `NoNewKeywordSwal`.. `sweetalert2` does. And that repo has lots of documentation for how to install. 

@mghifariy I can tell you that any library that interacts with the dom, like sweetalert2, will not work in react native because there there is no dom there. If you want to be able to use everything from the web in your mobile app you should read about [phonegap](http://phonegap.com/) but be aware that the User eXperience is not the same as a true native mobile app that uses the native UI like React Native does.

Still the error is unexpected and concerning, and we would greatly appreciate some more details on the environment where this error happens.. would you be able to share a repo or a [codepen](https://codepen.io/) or [codesandbox](https://codesandbox.io/) @mghifariy ? Either here or in a new issue in the sweetalert2 repo?
