### PR TITLE
Add TypeScript type definitions

### PR DESCRIPTION
**Pull request by toverux**
As promised :)

You'll see that I have taken a 1:1 mapping approach between the .d.ts files and the .js files. That's very useful to avoid big .d.ts files, is more adapted to type ESM, and helps a lot IDEs and the tooling (ie. you can create a .ts file at the root and import internal files of the library, they'll be typed, this is not possible otherwise).

You can remove `mounts.d.ts` though, as it's not actually exported anywhere. I just added it for the sake of symmetry.

If you find the .d.ts files to be too invasive in src/, we can go back to the single-file .d.ts approach like in SweetAlert and put it at the root, but as I said, this has drawbacks.

I added the minimal amount of packages/configuration to check the file (an npm script), but if you want to go further we can add:
 - a tsconfig.json to configure TypeScript
 - tslint and a tslint.json for the code style
 - a .ts file containing actual code that tests our type definitions in various scenarios. Useful to detect regressions.

### CODE REVIEW

**Comment by zenflow** [comment]
Closes #16 which I just opened because I didn't see this hahaha

**Comment by zenflow** [comment]
`type MaybeReact = string | ReactElement<any>`

MaybeReact is used for the shorthand arguments, and the params/options properties. It's not accurate in the case of the params/options properties because most of them can also be a DOM element. Is there a way to say "it will be a ReactElement or one of the types from the parent sweetalert"?

---

Also, for the child's return type, could we say "same as the parent" (whatever the parent happens to be)? Currently it looks like its [hard-coded to use that of sweetalert2](https://github.com/sweetalert2/sweetalert2-react-content/pull/15/files#diff-8cd3ab0092d5391c22d0599c7b5522d6R23), while the parent swal could be a different swal instance with a different return type.

**Comment by zenflow** [comment]
> If you find the .d.ts files to be too invasive in src/, we can go back to the single-file .d.ts approach like in SweetAlert and put it at the root, but as I said, this has drawbacks.

I wouldn't call it invasive, but since I don't currently use TypeScript, I fear the scenario where some of the internal types break and I have to figure out how to fix it, even though I don't really care. From the point-of-view of a consumer/user it's enough that there are types for the public API right? Can we maybe say "types for internals" is out of scope for now?

**Comment by zenflow** [comment]
> I added the minimal amount of packages/configuration to check the file (an npm script), but if you want to go further we can add:
>
> a tsconfig.json to configure TypeScript
> tslint and a tslint.json for the code style
> a .ts file containing actual code that tests our type definitions in various scenarios. Useful to detect regressions.

Yes, please go ahead! If this package is going to support TypeScript it should do it right! 

tsconfig and tslint should be quick to set up right?

If the `tests.ts` is a bit more effort feel free to follow up in another PR.

**Comment by toverux** [comment]
> MaybeReact is used for the shorthand arguments, and the params/options properties. It's not accurate in the case of the params/options properties because most of them can also be a DOM element. Is there a way to say "it will be a ReactElement or one of the types from the parent sweetalert"?

Very good point, I missed that while hacking around the type system with `Overwrite` / `Diff` (*).
It's indeed possible, I'll do that.

> Also, for the child's return type, could we say "same as the parent" (whatever the parent happens to be)? 

Unfortunately, there's no such thing as "parent" call signature. Those are different call sigs and therefore they have to be declared separately.

As a side note, `ReactSweetAlert` doesn't even `extend` anything, because the `SweetAlert2` is a module type. You can't extend a module type. That's why I merge them with `ReactSweetAlert & SweetAlert2`.

> From the point-of-view of a consumer/user it's enough that there are types for the public API right? Can we maybe say "types for internals" is out of scope for now?

You're right. I already did that for graphql-compose, which has a bunch of files. Only the externally-available are typed. I really just added mounts.d.ts because it was the only other file and for symmetry. But I agree, less files is better. Nobody needs this definition and there are no drawbacks in removing it.

> tsconfig and tslint should be quick to set up right?

Of course! Will do that. I prefer to ask because nobody likes having 25 configuration files.

> If the tests.ts is a bit more effort feel free to follow up in another PR.

Not really, it will just be a small file with a few `withReactContent()` calls of various form to ensure everything is good from the consumer point of view :)

----------------------

(*) I've had a hard time figuring out how to reuse a maximum types from SweetAlert2.

First, I needed to retrieve the type of the SweetAlert2 module itself. The library does not provide an interface for it's external public API that we can `extend`.

The other complication was `SweetAlertOptions`. Of course, I first tried to `extend` it to add `| ReactElement<any>` but this is not polymorphic:

```ts
interface ReactOptions extends SweetAlertOptions {
    title?: string | ReactElement<any>;
    text?: string | ReactElement<any>;
}
```

Resulting in:
```
error TS2430: Interface 'ReactOptions' incorrectly extends interface 'SweetAlertOptions'.
  Types of property 'title' are incompatible.
    Type 'ReactElement<any>' is not assignable to type 'string'.
```

That's totally understandable as `extend` is design to create a new type that is _assignable_ to the first one.

I also tried an intersection type: `SweetAlertOptions & ReactOptions`. It allows composition patterns that are frequently met in JavaScript.
But if you declare a variable with this type, you'll only be able to assign objects that have a compatible structure with `SweetAlertOptions` because the other type won't override the properties of the forst interface (there's no reason for that).

I was really aftraid of not having any means to express how the library works, other than copying the whole `SweetAlertOptions` interface contents. But TypeScript is really powerful and I've been able to do that, inspiring me from https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307871458.

Contrarily to the appearances, what you've done in this library is not a common pattern and is extremely hard to type, since it's not polymorphism, nor simple additive composition :)

**Comment by zenflow** [comment]
> As a side note, ReactSweetAlert doesn't even extend anything, because the SweetAlert2 is a module type. You can't extend a module type. That's why I merge them with ReactSweetAlert & SweetAlert2.

On that topic, check out sweetalert2/sweetalert2#1007

**Comment by toverux** [comment]
Just pushed a few commits that:

 - Reuse more types from SweetAlert2 (now there's no longer hardcoded `string` type)
 - Lint the .d.ts file(s)

I judged that it was not necessary to add a tsconfig.json (we don't need advanced TypeScript compiler configuration for now) nor a "test" .tsx file (types are simple enough I think).

**Comment by zenflow** [comment]
Rebased onto master and force-pushed. Original commits are in https://github.com/sweetalert2/sweetalert2-react-content/tree/original-type-all-the-things

**Comment by zenflow** [comment]
Any idea what the problem is with the check-dts script? 

The last 2 commits have different error messages..

**Comment by zenflow** [comment]
`git bisect` tells me:

> 7cb0bd767f46a69e6b4cffb8520ea1e45f45761e is the first bad commit

**Comment by limonte** [comment]
> node_modules/@types/acorn/index.d.ts(240,8): error TS2304: Cannot find name 'Symbol'.
> node_modules/@types/acorn/index.d.ts(240,28): error TS2304: Cannot find name 'Iterator'.

same issue here: https://github.com/sweetalert2/sweetalert2/pull/1020#issuecomment-373946812

**Comment by zenflow** [comment]
Many thanks @toverux! 🥂
